services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - lpb-network
    depends_on:
      - mysql
      - memcached

  memcached:
    image: memcached:latest
    restart: always
    ports:
      - "11211:11211"
    networks:
      - lpb-network

  nginx:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    networks:
      - lpb-network
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lpb-network

  mailer:
    image: mailhog/mailhog
    ports:
      - ":1025"
      - "8021:8025"
    networks:
      - lpb-network
    depends_on:
      - php

volumes:
  db_data:

networks:
    lpb-network:
        driver: bridge
